[workspace]
resolver = "3"
members = ["json", "core", "cli", "xtask"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
tavernlab-core = { path = "core" }
tavernlab-json = { path = "json" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
