/* Strings the Python locales do not carry yet.
 *
 * They live here rather than in `locales/*.json` on purpose: that file is
 * the desktop UI's contract and another branch edits it. Anything the two
 * UIs share is read from the server; only the new shell speaks from here.
 */
export const EXTRA = {
  uk: {
    'ui.nav.coach': 'Тренер',
    'ui.nav.games': 'Ігри',
    'ui.nav.deck': 'Колода',
    'ui.nav.meta': 'Гаунтлет',
    'ui.nav.tiers': 'Мета',
    'ui.tiers.title': 'Тір-лист симулятора',
    'ui.tiers.intro': 'Кожна колода гаунтлета зіграна проти кожної іншої. Тір — це смуга середнього вінрейту проти цього поля.',
    'ui.tiers.run': 'Порахувати тір-лист',
    'ui.tiers.rerun': 'Перерахувати',
    'ui.tiers.none': 'Тір-лист ще не рахували. Це важка задача: {pairs} пар по {games} боїв.',
    'ui.tiers.depth': 'Боїв на пару',
    'ui.tiers.computed': 'Пораховано {when}, по {games} боїв на пару',
    'ui.tiers.winrate': 'Проти поля',
    'ui.tiers.working': 'Рахую матрицю… це надовго; вкладку можна лишити відкритою.',
    'ui.tiers.vs_best': 'Найкращі матчапи',
    'ui.tiers.vs_worst': 'Найгірші матчапи',
    'ui.tiers.bands': 'Смуги: S ≥56%, A ≥52%, B ≥48%, C ≥44%, нижче — D.',
    'ui.meta.title': 'Гаунтлет',
    'ui.meta.format': 'Формат',
    'ui.meta.intro': 'Це не рейтинговий список та не знімок рейтингової таблиці. Це фіксований набір колод, з якими симулятор порівнює вашу колоду, коли ви натискаєте «Аналізувати» — саме звідти береться ваш відсоток.',
    'ui.meta.not_meta': 'Власних вінрейтів у цих колод тут немає: щоб їх дістати, довелося б збирати дані з HSReplay, а це поза межами проєкту (docs/DESIGN.md, U24).',
    'ui.meta.copy_code': 'Копіювати код',
    'ui.meta.copy_list': 'Копіювати список',
    'ui.meta.copied': 'Скопійовано',
    'ui.meta.use': 'Взяти собі',
    'ui.meta.no_code': 'Код не зібрати: у колоди є сайдборд, а гаунтлет не зберігає, якій карті він належить.',
    'ui.meta.code_partial': 'Код без сайдборду',
    'ui.meta.count': 'Колод: {n}',
    'ui.meta.cards': 'Карти',
    'ui.meta.curve': 'Крива мани',
    'ui.meta.your_wr': 'Ваш вінрейт',
    'ui.meta.no_wr': 'Проаналізуйте свою колоду, щоб побачити вінрейт проти кожної.',
    'ui.meta.sorted_by_wr': 'Відсортовано від найгіршого матчапу.',
    'ui.meta.show': 'Показати карти',
    'ui.meta.hide': 'Сховати карти',
    'ui.meta.unimplemented': 'сірим — карти, яких симулятор не знає',
    'ui.meta.empty': 'Для цього формату гаунтлета немає.',
    'ui.nav.settings': 'Налаштування',
    'ui.shell.tagline': 'Все рахується на вашому комп’ютері. Нічого не надсилається.',
    'ui.deck.none': 'Колоду не задано',
    'ui.deck.change': 'Змінити колоду',
    'ui.deck.set': 'Задати колоду',
    'ui.deck.dialog': 'Ваша колода',
    'ui.deck.save': 'Зберегти',
    'ui.deck.cancel': 'Скасувати',
    'ui.deck.resolving': 'Перевіряю…',
    'ui.deck.unimplemented': 'Ці карти є в базі, але симулятор ще не вміє їх розігрувати: {cards}',
    'ui.deck.illegal': 'Не дозволені у форматі «{fmt}»: {cards}',
    'ui.deck.missing': 'Невідомі карти: {cards}',
    'ui.deck.fmt_standard': 'Стандарт',
    'ui.deck.fmt_wild': 'Вайлд',
    'ui.deck.fmt_unknown': 'Формат невідомий',
    'ui.deck.ok': '{cls}, {n} карт',
    'ui.deck.analysed': 'Проаналізовано',
    'ui.deck.not_analysed': 'Ще не проаналізовано',

    'ui.coach.title': 'Що робити далі',
    'ui.coach.your_class': 'Ваш клас',
    'ui.coach.no_class': 'Ще без класу',
    'ui.coach.empty_title': 'Тут поки порожньо',
    'ui.coach.empty_body': 'Імпортуйте Power.log або задайте колоду — і тренер почне з чогось конкретного.',
    'ui.coach.tile_games': 'Ігор у базі',
    'ui.coach.tile_wr': 'Вінрейт',
    'ui.coach.tile_missed': 'Пропущених леталів',
    'ui.coach.tile_deck': 'Колода проти мети',
    'ui.coach.tile_missed_help': 'За останні {n} оглянутих ігор.',
    'ui.coach.tile_wr_help': 'За {n} останніми імпортованими іграми.',
    'ui.coach.recent': 'Останні ігри',
    'ui.coach.task_import': 'Імпортуйте свої ігри',
    'ui.coach.task_import_body': 'Без Power.log огляд робити нема на чому.',
    'ui.coach.task_deck': 'Задайте й проаналізуйте колоду',
    'ui.coach.task_deck_body': 'Муліган, читання суперника і поради тренера працюють від цієї телеметрії.',
    'ui.coach.task_lethal': 'Пропущений летал: {n}',
    'ui.coach.task_lethal_body': 'Це єдина мітка, яку ця збірка публікує без застережень. Перегляньте ці ходи.',
    'ui.coach.task_weak': 'Найгірший матчап: {n} ({v}%)',
    'ui.coach.task_weak_body': 'Подивіться, які карти просідають саме тут.',
    'ui.coach.task_review': 'Огляди ще будуються: {n}',
    'ui.coach.task_review_body': 'Аналіз іде локально, кілька секунд на гру.',
    'ui.coach.open': 'Відкрити',
    'ui.coach.no_tasks': 'Нічого термінового. Зіграйте ще кілька ігор.',

    'ui.games.import': 'Імпорт',
    'ui.games.count': 'Ігор: {n}',
    'ui.games.back': 'До списку ігор',
    'ui.game.review': 'Огляд',
    'ui.game.replay': 'Реплей',
    'ui.game.analyse_hint': 'Огляд цієї гри ще не робився.',
    'ui.game.working': 'Аналізую…',
    'ui.game.moment_open': 'Показати хід',
    'ui.game.ledger': 'Ходи',
    'ui.game.turn_col': 'Хід',
    'ui.game.mana_col': 'Мана лишилась',
    'ui.game.attacks_col': 'Невикористані атаки',
    'ui.game.notes_col': 'Нотатки',
    'ui.game.side_us': 'Ви',
    'ui.game.side_them': 'Суперник',
    'ui.game.ply': 'Дія {i} з {n}',
    'ui.game.inspector': 'Рішення',
    'ui.game.legend': 'Мітки',

    'ui.deck.tab_rating': 'Оцінка',
    'ui.deck.tab_improve': 'Покращення',
    'ui.deck.tab_mull': 'Муліган',
    'ui.deck.tab_opp': 'Суперник',
    'ui.deck.tab_coach': 'Нотатки тренера',
    'ui.deck.gate': 'Спершу проаналізуйте колоду — без телеметрії тут нема чого показувати.',
    'ui.deck.avg': 'Середній вінрейт',
    'ui.deck.rerun': 'Переаналізувати',
    'ui.deck.depth': 'Глибина симуляції',
    'ui.deck.depth_fast': 'Швидко (500)',
    'ui.deck.depth_normal': 'Звичайно (1000)',
    'ui.deck.depth_deep': 'Глибоко (2500)',
    'ui.mull.empty': 'Додайте карти з руки.',

    'ui.settings.diag': 'Діагностика',
    'ui.settings.diag_help': 'Локальні лічильники. Нічого нікуди не йде.',
    'ui.common.error': 'Помилка',
    'ui.common.close': 'Закрити',
  },
  en: {
    'ui.nav.coach': 'Coach',
    'ui.nav.games': 'Games',
    'ui.nav.deck': 'Deck',
    'ui.nav.meta': 'Gauntlet',
    'ui.nav.tiers': 'Meta',
    'ui.tiers.title': 'Simulator tier list',
    'ui.tiers.intro': 'Every gauntlet deck played against every other. The tier is a band of its average win rate against that field.',
    'ui.tiers.run': 'Compute the tier list',
    'ui.tiers.rerun': 'Recompute',
    'ui.tiers.none': 'Not computed yet. It is a heavy job: {pairs} pairs at {games} games each.',
    'ui.tiers.depth': 'Games per pair',
    'ui.tiers.computed': 'Computed {when}, {games} games per pair',
    'ui.tiers.winrate': 'Vs the field',
    'ui.tiers.working': 'Running the matrix — this takes a while; you can leave the tab open.',
    'ui.tiers.vs_best': 'Best matchups',
    'ui.tiers.vs_worst': 'Worst matchups',
    'ui.tiers.bands': 'Bands: S ≥56%, A ≥52%, B ≥48%, C ≥44%, below that D.',
    'ui.meta.title': 'Gauntlet',
    'ui.meta.format': 'Format',
    'ui.meta.intro': 'Not a tier list and not a ladder snapshot. It is the fixed set of decks the simulator runs yours against when you press Analyse — where your percentage comes from.',
    'ui.meta.not_meta': 'These decks carry no win rate of their own: getting one would mean scraping HSReplay, which is out of scope (docs/DESIGN.md, U24).',
    'ui.meta.copy_code': 'Copy code',
    'ui.meta.copy_list': 'Copy list',
    'ui.meta.copied': 'Copied',
    'ui.meta.use': 'Use as mine',
    'ui.meta.no_code': 'No code: this deck has a sideboard, and the gauntlet file does not record which card owns it.',
    'ui.meta.code_partial': 'Code omits the sideboard',
    'ui.meta.count': 'Decks: {n}',
    'ui.meta.cards': 'Cards',
    'ui.meta.curve': 'Mana curve',
    'ui.meta.your_wr': 'Your win rate',
    'ui.meta.no_wr': 'Analyse your deck to see your win rate against each.',
    'ui.meta.sorted_by_wr': 'Sorted worst matchup first.',
    'ui.meta.show': 'Show cards',
    'ui.meta.hide': 'Hide cards',
    'ui.meta.unimplemented': 'greyed — cards the simulator does not know',
    'ui.meta.empty': 'No gauntlet for this format.',
    'ui.nav.settings': 'Settings',
    'ui.shell.tagline': 'Everything is computed on your own machine. Nothing is sent anywhere.',
    'ui.deck.none': 'No deck set',
    'ui.deck.change': 'Change deck',
    'ui.deck.set': 'Set deck',
    'ui.deck.dialog': 'Your deck',
    'ui.deck.save': 'Save',
    'ui.deck.cancel': 'Cancel',
    'ui.deck.resolving': 'Checking…',
    'ui.deck.unimplemented': 'These cards are in the corpus, but the simulator cannot play them yet: {cards}',
    'ui.deck.illegal': 'Not legal in {fmt}: {cards}',
    'ui.deck.missing': 'Unknown cards: {cards}',
    'ui.deck.fmt_standard': 'Standard',
    'ui.deck.fmt_wild': 'Wild',
    'ui.deck.fmt_unknown': 'Unknown format',
    'ui.deck.ok': '{cls}, {n} cards',
    'ui.deck.analysed': 'Analysed',
    'ui.deck.not_analysed': 'Not analysed yet',

    'ui.coach.title': 'What to do next',
    'ui.coach.your_class': 'Your class',
    'ui.coach.no_class': 'No class yet',
    'ui.coach.empty_title': 'Nothing here yet',
    'ui.coach.empty_body': 'Import a Power.log or set a deck, and the coach will start with something concrete.',
    'ui.coach.tile_games': 'Games stored',
    'ui.coach.tile_wr': 'Win rate',
    'ui.coach.tile_missed': 'Missed lethals',
    'ui.coach.tile_deck': 'Deck vs meta',
    'ui.coach.tile_missed_help': 'Across the last {n} reviewed games.',
    'ui.coach.tile_wr_help': 'Across your last {n} imported games.',
    'ui.coach.recent': 'Recent games',
    'ui.coach.task_import': 'Import your games',
    'ui.coach.task_import_body': 'Without a Power.log there is nothing to review.',
    'ui.coach.task_deck': 'Set and analyse a deck',
    'ui.coach.task_deck_body': 'Mulligan, opponent reads and coach notes all run off that telemetry.',
    'ui.coach.task_lethal': 'Missed lethal: {n}',
    'ui.coach.task_lethal_body': 'It is the one label this build publishes without hedging. Go look at those turns.',
    'ui.coach.task_weak': 'Worst matchup: {n} ({v}%)',
    'ui.coach.task_weak_body': 'See which cards sink specifically here.',
    'ui.coach.task_review': 'Reviews still building: {n}',
    'ui.coach.task_review_body': 'The analysis runs locally, a few seconds per game.',
    'ui.coach.open': 'Open',
    'ui.coach.no_tasks': 'Nothing urgent. Play a few more games.',

    'ui.games.import': 'Import',
    'ui.games.count': 'Games: {n}',
    'ui.games.back': 'Back to games',
    'ui.game.review': 'Review',
    'ui.game.replay': 'Replay',
    'ui.game.analyse_hint': 'This game has not been reviewed yet.',
    'ui.game.working': 'Analysing…',
    'ui.game.moment_open': 'Show the ply',
    'ui.game.ledger': 'Turns',
    'ui.game.turn_col': 'Turn',
    'ui.game.mana_col': 'Mana left',
    'ui.game.attacks_col': 'Unused attacks',
    'ui.game.notes_col': 'Notes',
    'ui.game.side_us': 'You',
    'ui.game.side_them': 'Opponent',
    'ui.game.ply': 'Ply {i} of {n}',
    'ui.game.inspector': 'Decision',
    'ui.game.legend': 'Labels',

    'ui.deck.tab_rating': 'Rating',
    'ui.deck.tab_improve': 'Improvements',
    'ui.deck.tab_mull': 'Mulligan',
    'ui.deck.tab_opp': 'Opponent',
    'ui.deck.tab_coach': 'Coach notes',
    'ui.deck.gate': 'Analyse the deck first — without telemetry there is nothing to show here.',
    'ui.deck.avg': 'Average win rate',
    'ui.deck.rerun': 'Re-analyse',
    'ui.deck.depth': 'Simulation depth',
    'ui.deck.depth_fast': 'Fast (500)',
    'ui.deck.depth_normal': 'Normal (1000)',
    'ui.deck.depth_deep': 'Deep (2500)',
    'ui.mull.empty': 'Add the cards in your hand.',

    'ui.settings.diag': 'Diagnostics',
    'ui.settings.diag_help': 'Local counters. Nothing leaves the machine.',
    'ui.common.error': 'Error',
    'ui.common.close': 'Close',
  },
}
