/* Strings for this shell, on top of the ones the server serves.
 *
 * `locales/{lang}.json` is data: it ships beside the binary and can be
 * edited without a Node toolchain. These are the keys that describe this
 * front end's own furniture — tabs, panels, the diagnostics table — and
 * they live in the bundle so a screen never renders a raw key while the
 * translation file is still in flight.
 */
export const EXTRA = {
  uk: {
    'ui.nav.deck': 'Колода',
    'ui.nav.arena': 'Арена',
    'arena.title': 'Драфт Арени',
    'arena.blurb': 'Впишіть узяті карти та поточну трійку. Лічильники рахують те, що видно з даних карт; симуляція добирає колоду до 30 випадковими картами пулу сезону і грає проти згенерованого аренового поля. Число — порівняння між цими кандидатами на цьому драфті, не вінрейт сезону.',
    'arena.class': 'Клас',
    'arena.picked': 'Узяті карти',
    'arena.picked_hint': 'по одній назві в рядку',
    'arena.candidates': 'Трійка на вибір',
    'arena.count_btn': 'Лічильники',
    'arena.compare_btn': 'Порівняти симуляцією',
    'arena.compare_head': 'Симуляція',
    'arena.counters_head': 'Лічильники ({n} з {total} карт)',
    'arena.curve': 'Крива мани',
    'arena.two_drops': '2-манові істоти',
    'arena.taunts': 'Таунти',
    'arena.weapons': 'Зброя',
    'arena.removal': 'Жорсткий ремув (≈ за текстом)',
    'arena.damage_spells': 'Закляття з уроном (≈ за текстом)',
    'arena.aoe': 'AOE (≈ за текстом)',
    'arena.draw': 'Добір (≈ за текстом)',
    'arena.runes': 'Руни ЛС',
    'arena.counters_note': 'Рядки з «≈» читаються з англійського тексту карти, не з рушія. Це підказка, чого бракує, а не оцінка піку.',
    'arena.unimpl': 'Рушій не грає: {cards} — у симуляції їхні місця добере випадковий хвіст.',
    'arena.scores_head': 'Порівняння піків',
    'arena.games': '{n} ігор',
    'arena.behind': '−{d} в.п. від кращого',
    'arena.real': 'У симульованій колоді {n} з {total} карт — реальні піки; решта — випадковий хвіст із пулу сезону. На початку драфту різниця між кандидатами тоне в цьому шумі.',
    'arena.dropped': 'Не симулювалися (рушій не грає): {cards}.',
    'arena.group': '{card} — пакет: {pack}',
    'arena.cuts_note': 'Повна колода: п’ять карт, які крива й ключові слова пропонують вирізати на redraft (не симуляція). Натисніть, щоб прибрати з узятих, тоді впишіть п’ять нових.',
    'arena.cut': 'Вирізати {card}',
    'ui.nav.meta': 'Гаунтлет',
    'ui.nav.tiers': 'Мета',
    'ui.nav.settings': 'Налаштування',
    'ui.nav.history': 'Історія',
    'ui.nav.live': 'Гра',

    'ui.live.title': 'Порада під час гри',
    'ui.live.intro': 'Читає лог самої гри — той файл, який клієнт пише, коли це ввімкнено в log.config. Нічого не читається з памʼяті гри, не перехоплюється трафік і не емулюється введення. Колода береться з вкладки «Колода», бойовий тег — із самого логу, а завершені бої лягають в «Історію».',
    'ui.live.on': 'стежу',
    'ui.live.off': 'вимкнено',
    'ui.live.start': 'Почати',
    'ui.live.stop': 'Зупинити',
    'ui.live.logs_dir': 'Тека логів гри',
    'ui.live.logs_help': 'Потрібна тека Logs. Можна вказати й теку гри — там лежить log.config, яким вмикається детальне логування, і я зайду в Logs сама. Порожньо — візьму звичне для цієї системи місце.',
    'ui.live.auto': 'Вмикати стеження разом із застосунком',
    'ui.live.no_deck': 'Деккод ще не вказано: муліган і план ходу без нього рахувати нема з чого. Вставте колоду на вкладці «Колода».',
    'ui.live.nothing_yet': 'Ще нічого не видно — почніть бій.',

    'ui.history.title': 'Історія боїв',
    'ui.history.intro': 'Це єдина вкладка, де числа не пораховані, а зіграні. Її наповнює вкладка «Гра», читаючи лог самої гри: що вдалося прочитати — записано, чого ні — лишилося порожнім.',
    'ui.history.empty': 'Поки порожньо. Увімкніть стеження на вкладці «Гра» — кожен завершений бій ляже сюди сам.',
    'ui.history.games': 'Боїв',
    'ui.history.wins': 'Перемог',
    'ui.history.winrate': 'Вінрейт',
    'ui.history.unresolved': 'ще {n} без результату в лозі',
    'ui.history.too_few': 'замало боїв',
    'ui.history.floor': 'Вінрейт показано від 5 боїв. Менше — це не відсоток, а кілька боїв, і числа тут не вигадуються.',
    'ui.history.n_games_one': '{n} бій',
    'ui.history.n_games_few': '{n} бої',
    'ui.history.n_games_many': '{n} боїв',
    'ui.history.n_games_other': '{n} боїв',
    'ui.history.by_opponent': 'Проти класу',
    'ui.history.by_my_class': 'Вашим класом',
    'ui.history.by_deck': 'Проти колоди (за читанням гаунтлета)',
    'ui.history.recent': 'Останні бої',
    'ui.history.col_when': 'Коли',
    'ui.history.col_you': 'Ви',
    'ui.history.col_them': 'Суперник',
    'ui.history.col_result': 'Результат',
    'ui.history.col_turns': 'Ходів',
    'ui.history.col_read': 'Читання колоди',
    'ui.history.won': 'Перемога',
    'ui.history.lost': 'Поразка',
    'ui.history.unknown': 'Невідомо',
    'ui.history.coin': 'У вас була Монета — ви ходили другим',
    'ui.history.hits': '({hits} з {seen})',
    'ui.history.no_read': 'нічого не збіглося',
    'ui.history.file': 'Файл історії',
    'ui.history.file_note': 'Це звичайна база SQLite. Вона ваша: копіюйте, робіть бекап, відкривайте чим завгодно. Працює і sqlite3 history.sqlite \"select * from games\".',
    'ui.history.copy_path': 'Копіювати шлях',
    'ui.shell.tagline': 'Все рахується на вашому комп’ютері. Нічого не надсилається.',

    'ui.tiers.title': 'Тір-лист симулятора',
    'ui.tiers.intro': 'Кожна колода гаунтлета зіграна проти кожної іншої. Тір — це смуга середнього вінрейту проти цього поля.',
    'ui.tiers.run': 'Порахувати тір-лист',
    'ui.tiers.rerun': 'Перерахувати',
    'ui.tiers.none': 'Тір-лист ще не рахували: {pairs} пар по {games} боїв.',
    'ui.tiers.depth': 'Боїв на пару',
    'ui.tiers.computed': 'Пораховано {when}, по {games} боїв на пару',
    'ui.tiers.winrate': 'Проти поля',
    'ui.tiers.working': 'Рахую матрицю…',
    'ui.tiers.vs_best': 'Найкращі матчапи',
    'ui.tiers.vs_worst': 'Найгірші матчапи',
    'ui.tiers.bands': 'Смуги: S ≥56%, A ≥52%, B ≥48%, C ≥44%, нижче — D.',

    'ui.meta.format': 'Формат',
    'ui.meta.intro': 'Це не рейтинговий список та не знімок рейтингової таблиці. Це фіксований набір колод, з якими симулятор порівнює вашу колоду, коли ви натискаєте «Аналізувати» — саме звідти береться ваш відсоток.',
    'ui.meta.not_meta': 'Власних вінрейтів у цих колод тут немає: щоб їх дістати, довелося б збирати дані з HSReplay, а це поза межами проєкту (docs/DESIGN.md, U24).',
    'ui.meta.copy_code': 'Копіювати код',
    'ui.meta.copy_list': 'Копіювати список',
    'ui.meta.copied': 'Скопійовано',
    'ui.meta.use': 'Взяти собі',
    'ui.meta.no_code': 'Код не зібрати: у колоди є сайдборд, а гаунтлет не зберігає, якій карті він належить.',
    'ui.meta.code_partial': 'Код без сайдборду',
    'ui.meta.count': 'Колод: {n}, з них симулятор виставляє {playable}',
    'ui.meta.not_fielded': 'Симулятор не виставляє цю колоду: {cards}',
    'ui.meta.curve': 'Крива мани',
    'ui.meta.your_wr': 'Ваш вінрейт',
    'ui.meta.no_wr': 'Проаналізуйте свою колоду, щоб побачити вінрейт проти кожної.',
    'ui.meta.sorted_by_wr': 'Відсортовано від найгіршого матчапу.',
    'ui.meta.show': 'Показати карти',
    'ui.meta.hide': 'Сховати карти',
    'ui.meta.unimplemented': 'сірим — карти, яких симулятор не знає',
    'ui.meta.empty': 'Для цього формату гаунтлета немає.',

    'ui.field.title': 'Пораховано на {played} колодах поля з {all}',
    'ui.field.short_list': 'у списку {n} карт замість 30 — це неповний запис у файлі гаунтлета, а не прогалина в рушії',
    'ui.field.why': 'Колоду з нереалізованою картою симулятор не виставляє взагалі: викинути карту означало б зсунути вінрейт на невідому величину й видати це за вимір.',

    'ui.deck.none': 'Колоду не задано',
    'ui.deck.change': 'Змінити колоду',
    'ui.deck.dialog': 'Ваша колода',
    'ui.deck.save': 'Зберегти',
    'ui.deck.cancel': 'Скасувати',
    'ui.deck.resolving': 'Перевіряю…',
    'ui.deck.unimplemented': 'Ці карти є в базі, але симулятор ще не вміє їх розігрувати: {cards}',
    'ui.deck.illegal': 'Не дозволені у форматі «{fmt}»: {cards}',
    'ui.deck.missing': 'Невідомі карти: {cards}',
    'ui.deck.not_deckable': 'Це не карти для колоди: {cards}',
    'ui.deck.err_empty': 'Порожньо: вставте деккод.',
    'ui.deck.err_only_comments': 'Тут лише коментарі — самого деккоду немає.',
    'ui.deck.err_no_code': 'У вставленому тексті немає деккоду.',
    'ui.deck.err_truncated': 'Деккод обірваний — схоже, скопійовано не все.',
    'ui.deck.err_bad_header': 'Це не деккод.',
    'ui.deck.err_no_class': 'Не вдалося визначити клас колоди.',
    'ui.deck.fmt_standard': 'Стандарт',
    'ui.deck.fmt_wild': 'Вайлд',
    'ui.deck.fmt_arena': 'Арена (пул сезону)',
    'ui.deck.fmt_unknown': 'Формат невідомий',
    'ui.deck.ok': '{cls}, {n} карт',
    'ui.deck.tab_rating': 'Оцінка',
    'ui.improve.copy_deck': 'Копіювати нову колоду',
    'ui.deck.tab_improve': 'Покращення',
    'ui.deck.tab_mull': 'Муліган',
    'ui.deck.tab_opp': 'Суперник',
    'ui.deck.tab_coach': 'Нотатки тренера',
    'ui.deck.avg': 'Середній вінрейт',
    'ui.deck.rerun': 'Переаналізувати',
    'ui.deck.depth': 'Глибина симуляції',
    'ui.deck.depth_fast': 'Швидко (500)',
    'ui.deck.depth_normal': 'Звичайно (1000)',
    'ui.deck.depth_deep': 'Глибоко (2500)',
    'ui.mull.empty': 'Додайте карти з руки.',
    'ui.mull.why_expensive': 'дорога ({n} мани)',
    'ui.mull.why_cheap': 'дешева, тримає темп перших ходів',
    'ui.mull.why_vs_aggro_cheap': 'проти агресії рука мусить бути дешевою',
    'ui.mull.why_removal_vs_aggro': 'ремувал цінний проти їхніх ранніх міньйонів',
    'ui.mull.why_burn_vs_control': 'проти контролю пряма шкода краще йде в лице пізніше',
    'ui.mull.why_damage_both_ways': 'пряма шкода: і розмін, і добивання',
    'ui.mull.why_curve_body': 'тіло на криву — база темпу',
    'ui.mull.why_measured': 'виміряно: у стартовій руці змінює шанс на {n}',
    'ui.mull.why_no_data': 'замало ігор із цією картою в руці, щоб виміряти',

    'ui.settings.diag': 'Діагностика',
    'ui.settings.diag_help': 'Що вміє ця збірка рушія і що вона зробила з моменту запуску. Локально; нічого нікуди не йде.',
    'ui.settings.battletag': 'Ваш бойовий тег',
    'ui.settings.battletag_help': 'Зазвичай не потрібен: ватчер визначає його з логу. Впишіть, якщо в лозі так і не видно, котрий із двох гравців ви.',
    'ui.settings.cards': 'Карт у корпусі',
    'ui.settings.impl_standard': 'Реалізовано (Стандарт)',
    'ui.settings.impl_wild': 'Реалізовано (Вайлд)',
    'ui.settings.field_standard': 'Гаунтлет Стандарту (виставляється / всього)',
    'ui.settings.field_wild': 'Гаунтлет Вайлду (виставляється / всього)',
    'ui.settings.games': 'Боїв відіграно за сесію',
    'ui.settings.threads': 'Потоків симуляції',
    'ui.settings.data_home': 'Ваші дані',
    'ui.settings.root': 'Дані програми',

    'ui.common.error': 'Помилка',
    'ui.common.close': 'Закрити',
  },
  en: {
    'ui.nav.deck': 'Deck',
    'ui.nav.arena': 'Arena',
    'arena.title': 'Arena draft',
    'arena.blurb': 'Type the cards taken and the current offer. Counters read what the card data states; the simulation completes the deck to 30 with random season-pool cards and plays it against the generated Arena field. The number compares these candidates on this draft — it is not a season winrate.',
    'arena.class': 'Class',
    'arena.picked': 'Cards taken',
    'arena.picked_hint': 'one name per line',
    'arena.candidates': 'The offer',
    'arena.count_btn': 'Counters',
    'arena.compare_btn': 'Compare by simulation',
    'arena.compare_head': 'Simulation',
    'arena.counters_head': 'Counters ({n} of {total} cards)',
    'arena.curve': 'Mana curve',
    'arena.two_drops': '2-cost minions',
    'arena.taunts': 'Taunts',
    'arena.weapons': 'Weapons',
    'arena.removal': 'Hard removal (≈ from text)',
    'arena.damage_spells': 'Damage spells (≈ from text)',
    'arena.aoe': 'AOE (≈ from text)',
    'arena.draw': 'Card draw (≈ from text)',
    'arena.runes': 'DK runes',
    'arena.counters_note': 'Rows marked “≈” are read from the card’s English text, not from the engine. They point at gaps; they do not rate a pick.',
    'arena.unimpl': 'The engine does not play: {cards} — in the simulation their slots go to the random tail.',
    'arena.scores_head': 'Pick comparison',
    'arena.games': '{n} games',
    'arena.behind': '−{d} pp behind the best',
    'arena.real': '{n} of {total} cards in the simulated deck are real picks; the rest is a random tail from the season pool. Early in a draft the difference between candidates drowns in that noise.',
    'arena.dropped': 'Not simulated (the engine does not play them): {cards}.',
    'arena.group': '{card} — package: {pack}',
    'arena.cuts_note': 'Full deck: five cards the curve and keywords would rather cut on a redraft (not a simulation). Press to drop them from the taken list, then type the five new offers.',
    'arena.cut': 'Cut {card}',
    'ui.nav.meta': 'Gauntlet',
    'ui.nav.tiers': 'Meta',
    'ui.nav.settings': 'Settings',
    'ui.nav.history': 'History',
    'ui.nav.live': 'Live',

    'ui.live.title': 'Advice while you play',
    'ui.live.intro': "Reads the game's own log — the file the client writes when log.config asks it to. Nothing reads the game's memory, intercepts its traffic or types into it. The deck comes from the Deck tab, the battletag from the log itself, and finished games land in History.",
    'ui.live.on': 'watching',
    'ui.live.off': 'off',
    'ui.live.start': 'Start',
    'ui.live.stop': 'Stop',
    'ui.live.logs_dir': "The client's log directory",
    'ui.live.logs_help': 'The Logs folder. The game install works too — log.config sits there, and that is what turns verbose logging on; this follows Logs on its own. Leave empty for the usual place on this system.',
    'ui.live.auto': 'Start watching together with the app',
    'ui.live.no_deck': 'No deck code yet: the mulligan and the turn plan have nothing to work from. Paste a deck on the Deck tab.',
    'ui.live.nothing_yet': 'Nothing to see yet — start a game.',

    'ui.history.title': 'Match history',
    'ui.history.intro': 'The one tab where the numbers were played rather than computed. The Live tab fills it from the game\u2019s own log: what it could read is here, what it could not is blank.',
    'ui.history.empty': 'Nothing yet. Switch the watcher on in the Live tab and every finished match lands here by itself.',
    'ui.history.games': 'Games',
    'ui.history.wins': 'Wins',
    'ui.history.winrate': 'Win rate',
    'ui.history.unresolved': '{n} more the log never resolved',
    'ui.history.too_few': 'too few games',
    'ui.history.floor': 'A win rate appears from 5 games. Below that it is not a percentage, it is a handful of games, and nothing here is invented.',
    'ui.history.n_games_one': '{n} game',
    'ui.history.n_games_other': '{n} games',
    'ui.history.by_opponent': 'By opponent class',
    'ui.history.by_my_class': 'By your class',
    'ui.history.by_deck': 'By opponent deck (from the gauntlet read)',
    'ui.history.recent': 'Recent games',
    'ui.history.col_when': 'When',
    'ui.history.col_you': 'You',
    'ui.history.col_them': 'Opponent',
    'ui.history.col_result': 'Result',
    'ui.history.col_turns': 'Turns',
    'ui.history.col_read': 'Deck read',
    'ui.history.won': 'Win',
    'ui.history.lost': 'Loss',
    'ui.history.unknown': 'Unknown',
    'ui.history.coin': 'You held the Coin \u2014 you were on the draw',
    'ui.history.hits': '({hits} of {seen})',
    'ui.history.no_read': 'nothing matched',
    'ui.history.file': 'History file',
    'ui.history.file_note': 'An ordinary SQLite database. It is yours: copy it, back it up, open it with anything. sqlite3 history.sqlite \"select * from games\" works.',
    'ui.history.copy_path': 'Copy path',
    'ui.shell.tagline': 'Everything is computed on your own machine. Nothing is sent anywhere.',

    'ui.tiers.title': 'Simulator tier list',
    'ui.tiers.intro': 'Every gauntlet deck played against every other. The tier is a band of its average win rate against that field.',
    'ui.tiers.run': 'Compute the tier list',
    'ui.tiers.rerun': 'Recompute',
    'ui.tiers.none': 'Not computed yet: {pairs} pairs at {games} games each.',
    'ui.tiers.depth': 'Games per pair',
    'ui.tiers.computed': 'Computed {when}, {games} games per pair',
    'ui.tiers.winrate': 'Vs the field',
    'ui.tiers.working': 'Running the matrix…',
    'ui.tiers.vs_best': 'Best matchups',
    'ui.tiers.vs_worst': 'Worst matchups',
    'ui.tiers.bands': 'Bands: S ≥56%, A ≥52%, B ≥48%, C ≥44%, below that D.',

    'ui.meta.format': 'Format',
    'ui.meta.intro': 'Not a tier list and not a ladder snapshot. It is the fixed set of decks the simulator runs yours against when you press Analyse — where your percentage comes from.',
    'ui.meta.not_meta': 'These decks carry no win rate of their own: getting one would mean scraping HSReplay, which is out of scope (docs/DESIGN.md, U24).',
    'ui.meta.copy_code': 'Copy code',
    'ui.meta.copy_list': 'Copy list',
    'ui.meta.copied': 'Copied',
    'ui.meta.use': 'Use as mine',
    'ui.meta.no_code': 'No code: this deck has a sideboard, and the gauntlet file does not record which card owns it.',
    'ui.meta.code_partial': 'Code omits the sideboard',
    'ui.meta.count': 'Decks: {n}, of which the simulator can field {playable}',
    'ui.meta.not_fielded': 'The simulator cannot field this deck: {cards}',
    'ui.meta.curve': 'Mana curve',
    'ui.meta.your_wr': 'Your win rate',
    'ui.meta.no_wr': 'Analyse your deck to see your win rate against each.',
    'ui.meta.sorted_by_wr': 'Sorted worst matchup first.',
    'ui.meta.show': 'Show cards',
    'ui.meta.hide': 'Hide cards',
    'ui.meta.unimplemented': 'greyed — cards the simulator does not know',
    'ui.meta.empty': 'No gauntlet for this format.',

    'ui.field.title': 'Measured against {played} of the field’s {all} decks',
    'ui.field.short_list': 'the list holds {n} cards, not 30 — an incomplete entry in the gauntlet file rather than a gap in the engine',
    'ui.field.why': 'A deck holding a card the engine cannot play is not fielded at all: dropping the card would move the win rate by an unknown amount and report it as a measurement.',

    'ui.deck.none': 'No deck set',
    'ui.deck.change': 'Change deck',
    'ui.deck.dialog': 'Your deck',
    'ui.deck.save': 'Save',
    'ui.deck.cancel': 'Cancel',
    'ui.deck.resolving': 'Checking…',
    'ui.deck.unimplemented': 'These cards are in the corpus, but the simulator cannot play them yet: {cards}',
    'ui.deck.illegal': 'Not legal in {fmt}: {cards}',
    'ui.deck.missing': 'Unknown cards: {cards}',
    'ui.deck.not_deckable': 'These cannot go in a deck: {cards}',
    'ui.deck.err_empty': 'Nothing pasted: put a deck code in.',
    'ui.deck.err_only_comments': 'This is all comments — the deck code itself is missing.',
    'ui.deck.err_no_code': 'No deck code anywhere in the pasted text.',
    'ui.deck.err_truncated': 'The deck code ends early — it looks like part of it was left behind.',
    'ui.deck.err_bad_header': 'This is not a deck code.',
    'ui.deck.err_no_class': 'Cannot tell which class this deck is.',
    'ui.deck.fmt_standard': 'Standard',
    'ui.deck.fmt_wild': 'Wild',
    'ui.deck.fmt_arena': 'Arena (season pool)',
    'ui.deck.fmt_unknown': 'Unknown format',
    'ui.deck.ok': '{cls}, {n} cards',
    'ui.deck.tab_rating': 'Rating',
    'ui.improve.copy_deck': 'Copy new deck',
    'ui.deck.tab_improve': 'Improvements',
    'ui.deck.tab_mull': 'Mulligan',
    'ui.deck.tab_opp': 'Opponent',
    'ui.deck.tab_coach': 'Coach notes',
    'ui.deck.avg': 'Average win rate',
    'ui.deck.rerun': 'Re-analyse',
    'ui.deck.depth': 'Simulation depth',
    'ui.deck.depth_fast': 'Fast (500)',
    'ui.deck.depth_normal': 'Normal (1000)',
    'ui.deck.depth_deep': 'Deep (2500)',
    'ui.mull.empty': 'Add the cards in your hand.',
    'ui.mull.why_expensive': 'expensive ({n} mana)',
    'ui.mull.why_cheap': 'cheap, holds the early turns',
    'ui.mull.why_vs_aggro_cheap': 'against aggro the hand has to be cheap',
    'ui.mull.why_removal_vs_aggro': 'removal earns its keep against their early minions',
    'ui.mull.why_burn_vs_control': 'against control, direct damage is better spent on the face later',
    'ui.mull.why_damage_both_ways': 'direct damage: trades early, finishes late',
    'ui.mull.why_curve_body': 'a body on curve — the base of tempo',
    'ui.mull.why_measured': 'measured: kept in the opening hand it moves the odds by {n}',
    'ui.mull.why_no_data': 'too few games with this card in hand to measure',

    'ui.settings.diag': 'Diagnostics',
    'ui.settings.diag_help': 'What this build of the engine can do, and what it has done since it started. Local; nothing leaves the machine.',
    'ui.settings.battletag': 'Your battletag',
    'ui.settings.battletag_help': 'Usually not needed: the watcher learns it from the log. Fill it in if the log never says which of the two players you are.',
    'ui.settings.cards': 'Cards in the corpus',
    'ui.settings.impl_standard': 'Implemented (Standard)',
    'ui.settings.impl_wild': 'Implemented (Wild)',
    'ui.settings.field_standard': 'Standard gauntlet (fieldable / all)',
    'ui.settings.field_wild': 'Wild gauntlet (fieldable / all)',
    'ui.settings.games': 'Games simulated this session',
    'ui.settings.threads': 'Simulation threads',
    'ui.settings.data_home': 'Your data',
    'ui.settings.root': 'Program data',

    'ui.common.error': 'Error',
    'ui.common.close': 'Close',
  },
}
